imports:
    - { resource: config.yml }

framework:
    router:
        resource: '%kernel.project_dir%/app/config/routing_dev.yml'
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        security_errors:
          level: error
          type: stream
          path: '%dev_logs%/security_errors.log'
          channels: [security]

        doctrine_errors:
          level: error
          type: stream
          path: '%dev_logs%/doctrine_errors.log'
          channels: [doctrine]

        request_errors:
          level: error
          type: stream
          path: '%dev_logs%/request_errors.log'
          channels: [request]

        request_info:
          level: info
          type: stream
          path: '%dev_logs%/request_info.log'
          channels: [request]

        security_info:
          level: info
          type: stream
          path: '%dev_logs%/security_debug.log'
          channels: [security]

        doctrine_info:
          level: info
          type: stream
          path: '%dev_logs%/doctrine_debug.log'
          channels: [doctrine]

        main:
            type: stream
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            level: debug
            channels: ['!event']
        console:
            type: console
            process_psr_3_messages: false
            channels: ['!event', '!doctrine', '!console']
        # To follow logs in real time, execute the following command:
        # `bin/console server:log -vv`
        server_log:
            type: server_log
            process_psr_3_messages: false
            host: 127.0.0.1:9911
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type: firephp
        #    level: info
        #chromephp:
        #    type: chromephp
        #    level: info

#swiftmailer:
#    delivery_addresses: ['me@example.com']
