# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
      Symfony\Component\Security\Core\User\User: plaintext
      FOS\UserBundle\Model\UserInterface: bcrypt
      AppBundle\Entity\Utilisateur: bcrypt

    role_hierarchy:
      ROLE_ADMIN: ROLE_USER

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
          chain:
            providers: [in_memory, fos_userbundle]

        in_memory:
          memory:
            users:
              user:  { password: usr, roles: [ 'ROLE_USER' ] }
              admin: { password: adm, roles: [ 'ROLE_ADMIN' ] }

        fos_userbundle:
          id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
          pattern: ^/
          form_login:
            provider: chain_provider
            csrf_token_generator: security.csrf.token_manager
          logout: true
          anonymous: true
          remember_me:
              secret: '%secret%'
              lifetime: 604800 # 1 week in seconds
              path:     /
            # anonymous: ~
            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    access_control:
      - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
      - { path: ^/calendriers/edit/, role: ROLE_USER }
      - { path: /utilisateurs, role: ROLE_ADMIN, allow_if: "user.id == request.get('id')"  }
      - { path: /calendriers, role: ROLE_ADMIN }
      - { path: /formations, role: ROLE_ADMIN }
      - { path: /promotions, role: ROLE_ADMIN }
      - { path: /, role: ROLE_USER }